# yaml-language-server: $schema=https://cloud.dqops.com/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  profiling_checks:
    volume:
      profile_row_count:
        error:
          min_count: 90000
    schema:
      profile_column_count:
        error:
          expected_value: 9
  columns:
    transaction_id:
      type_snapshot:
        column_type: BIGINT
        nullable: true
      id: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 90000
        uniqueness:
          profile_distinct_percent:
            error:
              min_percent: 100.0
              max_percent: 100.0
          profile_duplicate_count:
            error:
              max_count: 0
        numeric:
          profile_min_in_range:
            error:
              from: 0.9
              to: 1.1
          profile_max_in_range:
            error:
              from: 90000.0
              to: 110000.0
          profile_mean_in_range:
            error:
              from: 45000.0
              to: 55000.0
    transaction_timestamp:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 90000
        uniqueness:
          profile_distinct_percent:
            error:
              min_percent: 100.0
              max_percent: 100.0
          profile_duplicate_count:
            error:
              max_count: 5
        datetime:
          profile_date_in_range_percent:
            parameters:
              min_date: 2023-12-30
              max_date: 2035-02-28
            error:
              min_percent: 100.0
    quantity:
      type_snapshot:
        column_type: INT
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 90000
        uniqueness:
          profile_distinct_count:
            error:
              min_count: 9
              max_count: 11
        accepted_values:
          profile_number_found_in_set_percent:
            parameters:
              expected_values:
              - 5
              - 8
              - 1
              - 3
              - 7
              - 10
              - 2
              - 6
              - 9
              - 4
            error:
              min_percent: 100.0
        numeric:
          profile_min_in_range:
            error:
              from: 0.9
              to: 1.1
          profile_max_in_range:
            error:
              from: 9.0
              to: 11.0
          profile_mean_in_range:
            error:
              from: 4.94
              to: 6.04
    unit_price:
      type_snapshot:
        column_type: DOUBLE
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 90000
        uniqueness:
          profile_distinct_count:
            error:
              min_count: 450
              max_count: 550
        numeric:
          profile_min_in_range:
            error:
              from: 6.75
              to: 8.26
          profile_max_in_range:
            error:
              from: 446.0
              to: 546.0
          profile_mean_in_range:
            error:
              from: 226.0
              to: 276.0
    total_amount:
      type_snapshot:
        column_type: DOUBLE
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 90000
        uniqueness:
          profile_distinct_percent:
            error:
              min_percent: 3.45
              max_percent: 6.41
        numeric:
          profile_min_in_range:
            error:
              from: 6.75
              to: 8.26
          profile_max_in_range:
            error:
              from: 4460.0
              to: 5460.0
          profile_mean_in_range:
            error:
              from: 1240.0
              to: 1520.0
    payment_method:
      type_snapshot:
        column_type: STRING
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 90000
        uniqueness:
          profile_distinct_count:
            error:
              min_count: 5
              max_count: 5
        accepted_values:
          profile_text_found_in_set_percent:
            parameters:
              expected_values:
              - Gift Card
              - Cash
              - Mobile Wallet
              - Credit Card
              - Debit Card
            error:
              min_percent: 100.0
        text:
          profile_text_min_length:
            error:
              from: 4
              to: 4
          profile_text_max_length:
            error:
              from: 12
              to: 14
          profile_text_mean_length:
            error:
              from: 8.45
              to: 10.3
        patterns:
          profile_texts_not_matching_regex_percent:
            parameters:
              regex: "^([A-Za-z]+( [A-Za-z]+)?)$"
            error:
              max_percent: 0.0
        pii:
          profile_contains_usa_phone_percent:
            error:
              max_percent: 0.0
          profile_contains_email_percent:
            error:
              max_percent: 0.0
        datatype:
          profile_detected_datatype_in_text:
            error:
              expected_datatype: texts
    customer_id:
      type_snapshot:
        column_type: BIGINT
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 90000
        uniqueness:
          profile_distinct_percent:
            error:
              min_percent: 7.0
              max_percent: 13.0
        numeric:
          profile_min_in_range:
            error:
              from: 0.9
              to: 1.1
          profile_max_in_range:
            error:
              from: 9000.0
              to: 11000.0
          profile_mean_in_range:
            error:
              from: 4490.0
              to: 5490.0
    store_id:
      type_snapshot:
        column_type: BIGINT
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 90000
        uniqueness:
          profile_distinct_count:
            error:
              min_count: 90
              max_count: 110
        numeric:
          profile_min_in_range:
            error:
              from: 0.9
              to: 1.1
          profile_max_in_range:
            error:
              from: 90.0
              to: 110.0
          profile_mean_in_range:
            error:
              from: 45.4
              to: 55.5
    product_id:
      type_snapshot:
        column_type: BIGINT
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 90000
        uniqueness:
          profile_distinct_count:
            error:
              min_count: 450
              max_count: 550
        numeric:
          profile_min_in_range:
            error:
              from: 0.9
              to: 1.1
          profile_max_in_range:
            error:
              from: 450.0
              to: 550.0
          profile_mean_in_range:
            error:
              from: 225.0
              to: 275.0
