# yaml-language-server: $schema=https://cloud.dqops.com/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    transaction_date:
      type_snapshot:
        column_type: DATE
        nullable: true
    store_id:
      type_snapshot:
        column_type: BIGINT
        nullable: true
    store_name:
      type_snapshot:
        column_type: STRING
        nullable: true
    product_category:
      type_snapshot:
        column_type: STRING
        nullable: true
    total_sales:
      type_snapshot:
        column_type: DOUBLE
        nullable: true
    units_sold:
      type_snapshot:
        column_type: BIGINT
        nullable: true
    num_transactions:
      type_snapshot:
        column_type: BIGINT
        nullable: true
    processing_date:
      type_snapshot:
        column_type: DATE
        nullable: true
