# yaml-language-server: $schema=https://cloud.dqops.com/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  columns:
    product_id:
      type_snapshot:
        column_type: BIGINT
        nullable: true
    product_name:
      type_snapshot:
        column_type: STRING
        nullable: true
    product_category:
      type_snapshot:
        column_type: STRING
        nullable: true
    product_subcategory:
      type_snapshot:
        column_type: STRING
        nullable: true
