services:
  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z-cpuv1
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - dqops_lakehouse_network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "${MARIADB_USER}", "-p${MARIADB_PASSWORD}"]
      interval: 10s
    volumes:
      - ./mariadb-data:/var/lib/mysql
    networks:
      - dqops_lakehouse_network

  hive-metastore:
    build: ./hive
    container_name: hive-metastore
    ports:
      - 9083:9083
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9083"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s 
    networks:
      - dqops_lakehouse_network

  spark:
    build:
      context: ./spark
      dockerfile: Dockerfile.spark-custom
    container_name: spark
    hostname: spark-master
    depends_on:
      minio:
        condition: service_healthy
      hive-metastore:
        condition: service_healthy
    environment:
      SPARK_MODE: master
      PYSPARK_PYTHON: python3
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "7077:7077"   # Spark master
      - "8081:8080"   # UI
    volumes:
      - ./airflow/data:/opt/airflow/data
      - ./spark/conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - dqops_lakehouse_network

  spark-worker:
    build:
      context: ./spark
      dockerfile: Dockerfile.spark-custom
    container_name: spark-worker
    depends_on:
      - spark
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: "2g"
      SPARK_WORKER_CORES: "4"
      SPARK_DAEMON_MEMORY: "1g"
      SPARK_DRIVER_MEMORY: "2g"
      SPARK_EXECUTOR_MEMORRY: 1G
      PYSPARK_PYTHON: python3
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ./airflow/data:/opt/airflow/data
      - ./spark/conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - dqops_lakehouse_network

  spark-worker-2:
    build:
      context: ./spark
      dockerfile: Dockerfile.spark-custom
    container_name: spark-worker-2
    depends_on:
      - spark
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: "2g"
      SPARK_WORKER_CORES: "4"
      SPARK_DAEMON_MEMORY: "1g"
      SPARK_DRIVER_MEMORY: "2g"
      SPARK_EXECUTOR_MEMORRY: 1G
      PYSPARK_PYTHON: python3
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ./airflow/data:/opt/airflow/data
      - ./spark/conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - dqops_lakehouse_network

  spark-thrift:
    build:
      context: ./spark
      dockerfile: Dockerfile.spark-custom
    container_name: spark-thrift
    command: [
      "/opt/bitnami/spark/sbin/start-thriftserver.sh",
      "--conf", "spark.cores.max=4"
    ]
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_EXECUTOR_MEMORY: 2g
      SPARK_EXECUTOR_CORES: 4
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "10000:10000"  # JDBC port
    volumes:
      - ./airflow/data:/opt/airflow/data
      - ./spark/conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    depends_on:
      spark:
        condition: service_started 
      #   condition: service_healthy
    networks:
      - dqops_lakehouse_network

networks:
  dqops_lakehouse_network:
    driver: bridge
