# yaml-language-server: $schema=https://cloud.dqops.com/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  timestamp_columns:
    event_timestamp_column: processing_date
    partition_by_column: processing_date
  incremental_time_window:
    daily_partitioning_recent_days: 7
    monthly_partitioning_recent_months: 1
  profiling_checks:
    volume:
      profile_row_count:
        error:
          min_count: 8814
    schema:
      profile_column_count:
        error:
          expected_value: 7
  monitoring_checks:
    daily:
      volume:
        daily_row_count:
          error:
            min_count: 8814
      schema:
        daily_column_count:
          error:
            expected_value: 7
  columns:
    transaction_date:
      type_snapshot:
        column_type: DATE
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 8810
        datetime:
          profile_date_in_range_percent:
            parameters:
              min_date: 1999-01-13
              max_date: 2035-02-28
            error:
              min_percent: 100.0
      monitoring_checks:
        daily:
          nulls:
            daily_nulls_count:
              error:
                max_count: 0
            daily_nulls_percent:
              error:
                max_percent: 0.0
            daily_not_nulls_count:
              error:
                min_count: 8810
          datetime:
            daily_date_in_range_percent:
              parameters:
                min_date: 1999-01-13
                max_date: 2035-02-28
              error:
                min_percent: 100.0
    store_name:
      type_snapshot:
        column_type: STRING
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 8810
        text:
          profile_text_min_length:
            error:
              from: 9
              to: 9
          profile_text_max_length:
            error:
              from: 9
              to: 9
          profile_text_mean_length:
            error:
              from: 8.1
              to: 9.9
        patterns:
          profile_texts_not_matching_regex_percent:
            parameters:
              regex: "^([A-Za-z]+ [0-9]+)$"
            error:
              max_percent: 0.0
        pii:
          profile_contains_usa_phone_percent:
            error:
              max_percent: 0.0
          profile_contains_email_percent:
            error:
              max_percent: 0.0
        datatype:
          profile_detected_datatype_in_text:
            error:
              expected_datatype: texts
      monitoring_checks:
        daily:
          nulls:
            daily_nulls_count:
              error:
                max_count: 0
            daily_nulls_percent:
              error:
                max_percent: 0.0
            daily_not_nulls_count:
              error:
                min_count: 8810
          text:
            daily_text_min_length:
              error:
                from: 9
                to: 9
            daily_text_max_length:
              error:
                from: 9
                to: 9
            daily_text_mean_length:
              error:
                from: 8.1
                to: 9.9
          patterns:
            daily_texts_not_matching_regex_percent:
              parameters:
                regex: "^([A-Za-z]+ [0-9]+)$"
              error:
                max_percent: 0.0
          pii:
            daily_contains_usa_phone_percent:
              error:
                max_percent: 0.0
            daily_contains_email_percent:
              error:
                max_percent: 0.0
          datatype:
            daily_detected_datatype_in_text:
              error:
                expected_datatype: texts
    product_category:
      type_snapshot:
        column_type: STRING
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 8810
        uniqueness:
          profile_distinct_count:
            error:
              min_count: 9
              max_count: 11
        accepted_values:
          profile_text_found_in_set_percent:
            parameters:
              expected_values:
              - Beauty
              - Automotive
              - Garden
              - Electronics
              - Groceries
              - Toys
              - Sports
              - Clothing
              - Home
              - Books
            error:
              min_percent: 100.0
        text:
          profile_text_min_length:
            error:
              from: 4
              to: 4
          profile_text_max_length:
            error:
              from: 10
              to: 12
          profile_text_mean_length:
            error:
              from: 6.33
              to: 7.74
        pii:
          profile_contains_usa_phone_percent:
            error:
              max_percent: 0.0
          profile_contains_email_percent:
            error:
              max_percent: 0.0
        datatype:
          profile_detected_datatype_in_text:
            error:
              expected_datatype: texts
      monitoring_checks:
        daily:
          nulls:
            daily_nulls_count:
              error:
                max_count: 0
            daily_nulls_percent:
              error:
                max_percent: 0.0
            daily_not_nulls_count:
              error:
                min_count: 8810
          uniqueness:
            daily_distinct_count:
              error:
                min_count: 9
                max_count: 11
          accepted_values:
            daily_text_found_in_set_percent:
              parameters:
                expected_values:
                - Beauty
                - Automotive
                - Garden
                - Electronics
                - Groceries
                - Toys
                - Sports
                - Clothing
                - Home
                - Books
              error:
                min_percent: 100.0
          text:
            daily_text_min_length:
              error:
                from: 4
                to: 4
            daily_text_max_length:
              error:
                from: 10
                to: 12
            daily_text_mean_length:
              error:
                from: 6.33
                to: 7.74
          pii:
            daily_contains_usa_phone_percent:
              error:
                max_percent: 0.0
            daily_contains_email_percent:
              error:
                max_percent: 0.0
          datatype:
            daily_detected_datatype_in_text:
              error:
                expected_datatype: texts
    total_sales:
      type_snapshot:
        column_type: DOUBLE
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 8810
        uniqueness:
          profile_distinct_percent:
            error:
              min_percent: 31.2
              max_percent: 58.0
        numeric:
          profile_min_in_range:
            error:
              from: 6.75
              to: 8.26
          profile_max_in_range:
            error:
              from: 7460.0
              to: 9120.0
          profile_mean_in_range:
            error:
              from: 1260.0
              to: 1550.0
          profile_median_in_range:
            parameters:
              percentile_value: 0.5
            error:
              from: 963.0
              to: 1170.0
      monitoring_checks:
        daily:
          nulls:
            daily_nulls_count:
              error:
                max_count: 0
            daily_nulls_percent:
              error:
                max_percent: 0.0
            daily_not_nulls_count:
              error:
                min_count: 8810
          uniqueness:
            daily_distinct_percent:
              error:
                min_percent: 31.2
                max_percent: 58.0
          numeric:
            daily_min_in_range:
              error:
                from: 6.75
                to: 8.26
            daily_max_in_range:
              error:
                from: 7460.0
                to: 9120.0
            daily_mean_in_range:
              error:
                from: 1260.0
                to: 1550.0
            daily_median_in_range:
              parameters:
                percentile_value: 0.5
              error:
                from: 963.0
                to: 1170.0
    units_sold:
      type_snapshot:
        column_type: BIGINT
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 8810
        uniqueness:
          profile_distinct_count:
            error:
              min_count: 22
              max_count: 26
        numeric:
          profile_min_in_range:
            error:
              from: 0.9
              to: 1.1
          profile_max_in_range:
            error:
              from: 23.4
              to: 28.6
          profile_mean_in_range:
            error:
              from: 5.0
              to: 6.12
          profile_median_in_range:
            parameters:
              percentile_value: 0.5
            error:
              from: 5.4
              to: 6.6
      monitoring_checks:
        daily:
          nulls:
            daily_nulls_count:
              error:
                max_count: 0
            daily_nulls_percent:
              error:
                max_percent: 0.0
            daily_not_nulls_count:
              error:
                min_count: 8810
          uniqueness:
            daily_distinct_count:
              error:
                min_count: 22
                max_count: 26
          numeric:
            daily_min_in_range:
              error:
                from: 0.9
                to: 1.1
            daily_max_in_range:
              error:
                from: 23.4
                to: 28.6
            daily_mean_in_range:
              error:
                from: 5.0
                to: 6.12
            daily_median_in_range:
              parameters:
                percentile_value: 0.5
              error:
                from: 5.4
                to: 6.6
    num_transactions:
      type_snapshot:
        column_type: BIGINT
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 8810
        uniqueness:
          profile_distinct_count:
            error:
              min_count: 5
              max_count: 5
        numeric:
          profile_min_in_range:
            error:
              from: 0.9
              to: 1.1
          profile_max_in_range:
            error:
              from: 4.5
              to: 5.5
          profile_mean_in_range:
            error:
              from: 0.918
              to: 1.12
          profile_median_in_range:
            parameters:
              percentile_value: 0.5
            error:
              from: 0.9
              to: 1.1
      monitoring_checks:
        daily:
          nulls:
            daily_nulls_count:
              error:
                max_count: 0
            daily_nulls_percent:
              error:
                max_percent: 0.0
            daily_not_nulls_count:
              error:
                min_count: 8810
          uniqueness:
            daily_distinct_count:
              error:
                min_count: 5
                max_count: 5
          numeric:
            daily_min_in_range:
              error:
                from: 0.9
                to: 1.1
            daily_max_in_range:
              error:
                from: 4.5
                to: 5.5
            daily_mean_in_range:
              error:
                from: 0.918
                to: 1.12
            daily_median_in_range:
              parameters:
                percentile_value: 0.5
              error:
                from: 0.9
                to: 1.1
    processing_date:
      type_snapshot:
        column_type: DATE
        nullable: true
      profiling_checks:
        nulls:
          profile_nulls_count:
            error:
              max_count: 0
          profile_nulls_percent:
            error:
              max_percent: 0.0
          profile_not_nulls_count:
            error:
              min_count: 8810
        uniqueness:
          profile_distinct_count:
            error:
              min_count: 1
              max_count: 1
        datetime:
          profile_date_in_range_percent:
            parameters:
              min_date: 2025-06-17
              max_date: 2035-03-19
            error:
              min_percent: 100.0
      monitoring_checks:
        daily:
          nulls:
            daily_nulls_count:
              error:
                max_count: 0
            daily_nulls_percent:
              error:
                max_percent: 0.0
            daily_not_nulls_count:
              error:
                min_count: 8810
          uniqueness:
            daily_distinct_count:
              error:
                min_count: 1
                max_count: 1
          datetime:
            daily_date_in_range_percent:
              parameters:
                min_date: 2025-06-17
                max_date: 2035-03-19
              error:
                min_percent: 100.0
