# yaml-language-server: $schema=https://cloud.dqops.com/dqo-yaml-schema/ConnectionYaml-schema.json
apiVersion: dqo/v1
kind: source
spec:
  provider_type: duckdb
  duckdb:
    read_mode: in_memory
    files_format_type: csv
    directories:
      files: /Users/dinhvietquyen1803/Data_Engineering/dqops_lakehouse/airflow/data
    storage_type: local
    aws_authentication_mode: default_credentials
  schedules:
    profiling:
      cron_expression: 0 1 1 * *
    monitoring_daily:
      cron_expression: 0 12 * * *
    monitoring_monthly:
      cron_expression: 0 12 * * *
    partitioned_daily:
      cron_expression: 0 12 * * *
    partitioned_monthly:
      cron_expression: 0 12 * * *
  incident_grouping:
    grouping_level: table_dimension_category
    minimum_severity: warning
    max_incident_length_days: 60
    mute_for_days: 60
